export const cities = {
  bali: {
    slug: 'bali',
    name: 'Bali',
    country: 'Indonesia',
    countryCode: 'ID',
    active: true,
    brandColor: '#21827e',
    bg: '#f7fdfa',
    sloganKey: 'dashboard.cities.bali',
    center: [-8.4095, 115.1889],
    zoom: 10,
    features: { surf: true, heatmap: true, aiBrief: true },
    apis: {
      incidents: import.meta.env.VITE_INCIDENTS_API_URL || '/api/incidents',
      security: import.meta.env.VITE_SECURITY_REPORT_URL || '/api/security',
      chat: import.meta.env.VITE_SECURITY_CHAT_URL || '/api/security/chat',
    },
  },
  jakarta: {
    slug: 'jakarta',
    name: 'Jakarta',
    country: 'Indonesia',
    countryCode: 'ID',
    active: false,
    brandColor: '#365278',
    bg: '#f6fafd',
    sloganKey: 'dashboard.cities.jakarta',
    center: [-6.2088, 106.8456],
    zoom: 11,
    features: { surf: false, heatmap: true, aiBrief: true },
    apis: {},
  },
  bangkok: {
    slug: 'bangkok',
    name: 'Bangkok',
    country: 'Thailand',
    countryCode: 'TH',
    active: false,
    brandColor: '#e53935',
    bg: '#fef9f7',
    sloganKey: 'dashboard.cities.bangkok',
    center: [13.7563, 100.5018],
    zoom: 11,
    features: { surf: false, heatmap: true, aiBrief: true },
    apis: {},
  },
  singapore: {
    slug: 'singapore',
    name: 'Singapore',
    country: 'Singapore',
    countryCode: 'SG',
    active: false,
    brandColor: '#35b9e3',
    bg: '#f7fbfe',
    sloganKey: 'dashboard.cities.singapore',
    center: [1.3521, 103.8198],
    zoom: 12,
    features: { surf: false, heatmap: true, aiBrief: true },
    apis: {},
  },
  danang: {
    slug: 'danang',
    name: 'Da Nang',
    country: 'Vietnam',
    countryCode: 'VN',
    active: false,
    brandColor: '#17ad5b',
    bg: '#f7fefb',
    sloganKey: 'dashboard.cities.danang',
    center: [16.0544, 108.2022],
    zoom: 12,
    features: { surf: false, heatmap: true, aiBrief: true },
    apis: {},
  },
  kl: {
    slug: 'kl',
    name: 'Kuala Lumpur',
    country: 'Malaysia',
    countryCode: 'MY',
    active: false,
    brandColor: '#6f35e3',
    bg: '#faf7fe',
    sloganKey: 'dashboard.cities.kl',
    center: [3.139, 101.6869],
    zoom: 12,
    features: { surf: false, heatmap: true, aiBrief: true },
    apis: {},
  },
}

export const cityList = Object.values(cities)
